/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.process.tracker;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Narendra
 */

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    static DefaultTableModel dtm = new DefaultTableModel(0, 0);
    String header[] = new String[]{"Process Name", "PID", "Session Name", "Session #",
        "Memory"};

    public Main() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System Process Tracker");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(660, 520));
        setMinimumSize(new java.awt.Dimension(660, 520));
        setPreferredSize(new java.awt.Dimension(660, 520));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("System Process Tracker");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Process Name", "PID", "Session Name", "Session #", "Memory"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(216, 216, 216));
        jLabel2.setText("Narendra Kamath");
        jLabel2.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            dtm.setColumnIdentifiers(header);
            String line;
            //sjTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            dtm.setRowCount(0);
            String txt = "", txt1 = "";
            Process p = Runtime.getRuntime().exec(System.getenv("windir") + "\\system32\\" + "tasklist.exe");
            BufferedReader input
                    = new BufferedReader(new InputStreamReader(p.getInputStream()));
            //input.readLine();
            while ((line = input.readLine()) != null) {
                txt1 = line.trim().replaceAll(" +", " ");
                txt1 = txt1.replaceAll("=", "");
                txt1 = txt1.replaceAll("Image Name PID Session Name Session# Mem Usage", "");

                if (txt1.trim().length() >= 1) {
                    txt1 = txt1.substring(0, txt1.length() - 2);
                    char[] cs = txt1.toCharArray();
                    for (int i = 0; i < cs.length - 1; i++) {
                        if (Character.isSpace(cs[i])) {
                            if (Character.isDigit(cs[i + 1]) && Character.isLetter(cs[i - 1])) {
                                cs[i] = '\t';
                            }
                            if (Character.isDigit(cs[i - 1]) && Character.isLetter(cs[i + 1])) {
                                cs[i] = '\t';
                            }
                            if (Character.isDigit(cs[i - 1]) && Character.isDigit(cs[i + 1])) {
                                cs[i] = '\t';
                            }
                        }
                    }
                    txt1=String.valueOf(cs);
                    //txt += txt1+ "\n";
                    dtm.addRow(new Object[]{"" + txt1.split("\t")[0], txt1.split("\t")[1], "" + txt1.split("\t")[2], "" + txt1.split("\t")[3],
                            "" + txt1.split("\t")[4]+" K"});
                }
            }
            input.close();
            jTable1.setModel(dtm);
           jTable1.setPreferredScrollableViewportSize(jTable1.getPreferredSize());
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            dtm.setColumnIdentifiers(header);
            String line;
            //sjTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            dtm.setRowCount(0);
            String txt = "", txt1 = "";
            Process p = Runtime.getRuntime().exec(System.getenv("windir") + "\\system32\\" + "tasklist.exe");
            BufferedReader input
                    = new BufferedReader(new InputStreamReader(p.getInputStream()));
            //input.readLine();
            while ((line = input.readLine()) != null) {
                txt1 = line.trim().replaceAll(" +", " ");
                txt1 = txt1.replaceAll("=", "");
                txt1 = txt1.replaceAll("Image Name PID Session Name Session# Mem Usage", "");

                if (txt1.trim().length() >= 1) {
                    txt1 = txt1.substring(0, txt1.length() - 2);
                    char[] cs = txt1.toCharArray();
                    for (int i = 0; i < cs.length - 1; i++) {
                        if (Character.isSpace(cs[i])) {
                            if (Character.isDigit(cs[i + 1]) && Character.isLetter(cs[i - 1])) {
                                cs[i] = '\t';
                            }
                            if (Character.isDigit(cs[i - 1]) && Character.isLetter(cs[i + 1])) {
                                cs[i] = '\t';
                            }
                            if (Character.isDigit(cs[i - 1]) && Character.isDigit(cs[i + 1])) {
                                cs[i] = '\t';
                            }
                        }
                    }
                    txt1=String.valueOf(cs);
                    //txt += txt1+ "\n";
                    dtm.addRow(new Object[]{"" + txt1.split("\t")[0], txt1.split("\t")[1], "" + txt1.split("\t")[2], "" + txt1.split("\t")[3],
                            "" + txt1.split("\t")[4]+" K"});
                }
            }
            input.close();
            jTable1.setModel(dtm);
           jTable1.setPreferredScrollableViewportSize(jTable1.getPreferredSize());
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
